
export const INCREASE_PRICE = 'INCREASE_PRICE'
export const DECREASE_PRICE = 'DECREASE_PRICE'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const INCREASE_CART = 'INCREASE_CART'
export const DECREASE_CART = 'DECREASE_CART'